In [1]:
a = 10
b = 100000000000000000000000000000000000000000

print(a)
print(b)

10
100000000000000000000000000000000000000000


In [ ]:
c = 3 + 4j

print(c.real) # 실수부 3.0
print(c.imag) # 허수부 4.0

3.0
4.0


In [4]:
# decimal 모듈안에 Decimal함수를 메모리에 로드
# 파이썬 언어가 제공하는 객체중 내장객체가 아닌것들은 import 후 사용
from decimal import Decimal

a = Decimal("0.1") # 인자값을 float으로 전달하면 전달하는 순간 오차가 발생하니 문자열로 입력한다.
b = Decimal("0.2")

print(a + b)

print(0.1 + 0.2 == 0.3) # False

print(Decimal("0.1") + Decimal("0.2") == Decimal("0.3")) # True

0.3
False
True


In [5]:
from fractions import Fraction

f = Fraction(1, 3)

print(f)

# 분수계산의 예
a = Fraction(1, 3)
b = Fraction(1, 6)
c = a + b
print(c)

d = a*b
print(d)

# 분수를 실수로 변환
print(float(c))
print(float(d))

1/3
1/2
1/18
0.5
0.05555555555555555


In [7]:
a = -1
b = 0
c = 1
d = 2
e = 0.1

print(bool(a)) # True
print(bool(b)) # False
print(bool(c)) # True
print(bool(d)) # True
print(bool(e)) # True

True
False
True
True
True


In [8]:
n = 10
print(n.bit_length()) # 10의 이진수 값(1010)의 길이

# bin()함수는 인자로 입력된 10진수의 2진수 문자열을 반환한다.
# 이진수 문자열 앞에 binary를 뜻하는 "0b"접두사를 앞에 붙여서 반환한다.
print(bin(n)) #0b1010 "0b" + "1010"

# bit_length()메서드는 n이라는 숫자 객체를 만들어야 존재하는 것이고,
# bin() 함수는 n객체와 상관없는 독립된 함수 객체이다.

print(bin(9)) # n과 상관없이 독립적으로 사용가능

4
0b1010
0b1001


In [9]:
print(pow(2, 3)) # 거듭제곱 int로 반환
print(divmod(10, 3)) # 몫과 나머지를 tuple로 반환
print(round(3.14159, 2)) # 반올림된 실수값을 반환
print(abs(-10)) # 절대값을 반환(반환 타입은 인자값과 같은 타입)

8
(3, 1)
3.14
10


In [10]:
pip install numpy

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ------ --------------------------------- 2.1/12.4 MB 9.3 MB/s eta 0:00:02
   ----------------------------- ---------- 9.2/12.4 MB 21.3 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 25.8 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [15]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])
print(a + b) 
print(a * b)
print(a @ b)  

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [16]:
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6]])   # 2행3열

b = np.array([[10],
              [20],
              [30]])        # 3행1열

print(a @ b) # 결과는 2행1열
# [1×10 + 2×20 + 3×30]
# [4×10 + 5×20 + 6×30]

[[140]
 [320]]
